// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAld-KlTUc7M0sR99u4erVLZP3-YlnySpU',
    appId: '1:699140364706:web:b6183c72d0bf3602ae7afb',
    messagingSenderId: '699140364706',
    projectId: 'fbtest-ce6f3',
    authDomain: 'fbtest-ce6f3.firebaseapp.com',
    databaseURL: 'https://fbtest-ce6f3-default-rtdb.firebaseio.com',
    storageBucket: 'fbtest-ce6f3.appspot.com',
    measurementId: 'G-QBMPMHVEZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzvYW1q0t23_4Otl7ccBnTqqQ_gKs-Kgc',
    appId: '1:699140364706:android:f08b9bf4634d4e1aae7afb',
    messagingSenderId: '699140364706',
    projectId: 'fbtest-ce6f3',
    databaseURL: 'https://fbtest-ce6f3-default-rtdb.firebaseio.com',
    storageBucket: 'fbtest-ce6f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7ot4bqulTvchU5bEFmOjKfJDoklBI_lo',
    appId: '1:699140364706:ios:1ed8c72649c81cbfae7afb',
    messagingSenderId: '699140364706',
    projectId: 'fbtest-ce6f3',
    databaseURL: 'https://fbtest-ce6f3-default-rtdb.firebaseio.com',
    storageBucket: 'fbtest-ce6f3.appspot.com',
    iosClientId: '699140364706-maajthpt0na0h70pdf6a4osjrm86evnb.apps.googleusercontent.com',
    iosBundleId: 'com.example.codecamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7ot4bqulTvchU5bEFmOjKfJDoklBI_lo',
    appId: '1:699140364706:ios:1ed8c72649c81cbfae7afb',
    messagingSenderId: '699140364706',
    projectId: 'fbtest-ce6f3',
    databaseURL: 'https://fbtest-ce6f3-default-rtdb.firebaseio.com',
    storageBucket: 'fbtest-ce6f3.appspot.com',
    iosClientId: '699140364706-maajthpt0na0h70pdf6a4osjrm86evnb.apps.googleusercontent.com',
    iosBundleId: 'com.example.codecamp',
  );
}
